# Generated by Django 5.1.5 on 2025-03-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("image_url", models.URLField()),
            ],
        ),
    ]
