# Generated by Django 5.1.5 on 2025-03-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_upload", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="upload_time",
            new_name="upload_date",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="image_url",
            new_name="url",
        ),
    ]
