# Generated by Django 5.1.5 on 2025-03-18 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_upload", "0002_rename_image_id_image_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
