# Generated by Django 5.1.5 on 2025-03-18 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_upload", "0003_image_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="upload_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
