"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
VM_IP = config('VM_IP', default='*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# VM_IP = config('VM_IP', default='127.0.0.1')

ALLOWED_HOSTS = [VM_IP,'localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "healthz",
    "tests",
    "image_upload",
]

MIDDLEWARE = [
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "webapp.urls"

WSGI_APPLICATION = "webapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', config('DB_NAME', default='csye6225')),
        'USER': os.getenv('DB_USER', config('DB_USER', default='admin')),
        'PASSWORD': os.getenv('DB_PASS', config('DB_PASS', default='default_password')),
        'HOST': os.getenv('DB_HOST', config('DB_HOST', default='localhost')),  # Use RDS endpoint, NOT localhost
        'PORT': os.getenv('DB_PORT', config('DB_PORT', default='3306')),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"