# Generated by Django 5.1.5 on 2025-01-27 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                ("check_id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
