name: packer_setup

on:
  pull_request:
    branches:
      - main

jobs:
    packer:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup `packer`
          uses: hashicorp/setup-packer@main
          id: setup

        - name: Initialize Packer
          run: packer init setup.pkr.hcl
          working-directory: ./webapp/packer_setup

        - name: Run packer fmt
          id: packer_fmt
          run: |
            packer fmt -diff -check setup.pkr.hcl
          continue-on-error: true
          working-directory: ./webapp/packer_setup

        - name: Fail if packer fmt modifies files
          if: steps.packer_fmt.outcome == 'failure'
          run: |
            echo "Packer fmt modified files. Please run 'packer fmt' locally and commit the changes."
            exit 1
          working-directory: ./webapp/packer_setup
#
#        - name: Create Test Files and Zip
#          run: |
#            touch test.txt
#            zip webapp.zip test.txt

        - name: Validate Packer template
          env:
            Region: ${{ variables.AWS_REGION }}
            Instance_Type: ${{ variables.INSTANCE_TYPE }}
            Source_AMI: ${{ secrets.AWS_SOURCE_AMI }}
            AMI_Name: ${{ variables.AMI_NAME }}
            AMI_Description: ${{ variables.AMI_DESCRIPTION }}
            SSH_Username: ${{ variables.SSH_USERNAME }}
            Volume_Size: ${{ variables.VOLUME_SIZE }}
            Volume_Type: ${{ variables.VOLUME_TYPE }}
            AWS_Account_IDs: ${{ secrets.AWS_ACCOUNT_IDS }}
          run: |
            packer validate \
                -var "region=Region" \
                -var "instance_type=Instance_Type" \
                -var "source_ami=Source_AMI" \
                -var "ami_name=AMI_Name" \
                -var "ami_description=AMI_Description" \
                -var "ssh_username=SSH_Username" \
                -var "volume_size=Volume_Size" \
                -var "volume_type=Volume_Type" \
                -var "account_ids=AWS_Account_IDs" \
                setup.pkr.hcl