name: packer_setup

on:
  pull_request:
    branches:
      - main

jobs:
    packer:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup `packer`
          uses: hashicorp/setup-packer@main
          id: setup

        - name: Initialize Packer
          run: packer init setup.pkr.hcl
          working-directory: ./webapp/packer_setup

        - name: Run packer fmt
          id: packer_fmt
          run: |
            packer fmt -diff -check setup.pkr.hcl
          continue-on-error: true
          working-directory: ./webapp/packer_setup

        - name: Fail if packer fmt modifies files
          if: steps.packer_fmt.outcome == 'failure'
          run: |
            echo "Packer fmt modified files. Please run 'packer fmt' locally and commit the changes."
            exit 1
          working-directory: ./webapp/packer_setup


        - name: Validate Packer template
          env:
            Source_AMI: ${{ secrets.AWS_SOURCE_AMI }}
            AWS_Account_IDs: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
            GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
          run: |
            packer validate \
              -var "source_ami=${Source_AMI}" \
              -var "account_ids=[\"${AWS_Account_IDs}\"]" \
              -var "google_project_id=${GOOGLE_PROJECT_ID}" \
             -var "db_host=${DB_HOST}" \
            -var "db_user=${DB_USER}" \
            -var "db_password=${DB_PASSWORD}" \
            -var "db_name=${DB_NAME}" \
              setup.pkr.hcl
          working-directory: ./webapp/packer_setup