name: packer_setup

on:
  pull_request:
    branches:
      - main

jobs:
    packer:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup `packer`
          uses: hashicorp/setup-packer@main
          id: setup

        - name: Initialize Packer
          run: packer init setup.pkr.hcl
          working-directory: ./webapp/packer_setup

        - name: Run packer fmt
          id: packer_fmt
          run: |
            packer fmt -diff -check setup.pkr.hcl
          continue-on-error: true
          working-directory: ./webapp/packer_setup

        - name: Fail if packer fmt modifies files
          if: steps.packer_fmt.outcome == 'failure'
          run: |
            echo "Packer fmt modified files. Please run 'packer fmt' locally and commit the changes."
            exit 1
          working-directory: ./webapp/packer_setup
#
#        - name: Create Test Files and Zip
#          run: |
#            touch test.txt
#            zip webapp.zip test.txt

        - name: Validate Packer template
          env:
            Source_AMI: ${{ secrets.AWS_SOURCE_AMI }}
            AWS_Account_IDs: ${{ secrets.AWS_ACCOUNT_IDS }}
          run: |
            packer validate \
                -var "region=$AWS_REGION" \
                -var "instance_type=$INSTANCE_TYPE" \
                -var "source_ami=Source_AMI" \
                -var "ami_name=$AMI_NAME" \
                -var "ami_description=$AMI_DESCRIPTION" \
                -var "ssh_username=$SSH_USERNAME" \
                -var "volume_size=$VOLUME_SIZE" \
                -var "volume_type=$VOLUME_TYPE" \
                -var "account_ids=AWS_Account_IDs" \
                setup.pkr.hcl